#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define SPEED 10
#define PLAYER_WIDTH 128
#define PLAYER_HEIGHT 128
#define BULLET_WIDTH 128
#define BULLET_HEIGHT 128
#define BULLET_SPEED 15
#define ENEMY_SPEED 5
#define ENEMY_WIDTH 128
#define ENEMY_HEIGHT 128
#define NUM_SOUNDS 2
#define MAX_SND_CHANNELS 8
#define MENU_TEXT "Press Space to start"
#define MENU_TXT_WIDTH 500
#define MENU_TXT_HEIGHT 50
